# print("hello world")

print("hello world ." , " hello ji")

# print(25)
# print(25+15)
# print(25/5)



# new things


name="affanmalik"
age=18
print("age") # agr ye likhoge to age likha aga 
print(age )# agr asa likhoge to age ki value ok 
print(type(name))
print(type(age))

# new

print("new")
name1="affan"
name2='affan'
name3='''affan'''
name4= None
name5= True

print(name1)
print(name2)
print(name3)
print(type(name4))
print(type(name5))


